### ISSUE TITLE
1,715, not 1,709

### ISSUE THREAD

**Issue by troyth** [provolot/guggcolors#1]
Re: your README never going to do stuff... in the last bullet point, it should be 1,715, not 1,709, images on flickr. Everything is in the data set, including the 6 finalists. Also, you (or I) should get your students to do this ;)

**Comment by dantaeyoung** [comment]
@troyth Ah, good point; fixed. Are the 6 finalists identified by their id somewhere?

**Comment by troyth** [comment]
Yes, check out the finalist gallery on designguggenheimhelsinki.org
